### PR TITLE
check mysql using PDO now

### LINKED ISSUE #475: MySQL Check in installer shows 'failed', with a green checkbox
THe mysql check in the installer on page_modcheck.php lists as 'Failed' on PHP 7.1, but next to it there is a green check, and there are no issues with the installation.

### PR DESCRIPTION
**Pull request by fiammybe**
fix #475

### CODE REVIEW

**Comment by fiammybe** [comment]
As a matter of fact, you are correct! I noticed the issue because of an incongruity between the checkbox and the status, and with this change the 2 are aligned again : both ok. But you are right that the image won't ever change with this code... I need to improve on that

**Comment by skenow** [comment]
It looks like the image selection is reversed - 'no' will display if the test is successful, 'yes' if it is not. The alt text could also be changed based on the result.

**Comment by fiammybe** [comment]
You're totally correct. And I also missed some cases. I'll try to make this a bit more structured before committing again. a function here and there wouldn't hurt :-)

File: htdocs/install/page_modcheck.php [hunk 1]
```diff
@@ -63,37 +64,51 @@ function xoDiagIfWritable( $path) {
...
-<h4><?php printf( PHP_EXTENSION, 'PCRE' ); ?>:&nbsp; <?php echo xoDiag( extension_loaded( 'pcre' ) ? 1 : -1 ); ?>
-<img src="img/yes.png" alt="Success" class="rootimg" /></h4>
-<div class="clear">&nbsp;</div>
-<h4>file_uploads:&nbsp; <?php echo xoDiagBoolSetting( 'file_uploads', true ); ?>
-<img src="img/yes.png" alt="Success" class="rootimg" /></h4>
+<?php foreach($requirements_array as &$requirement)
+	 {
+	 ?>
+<h4><?php echo $requirement['description']; ?>:&nbsp; <?php echo xoDiag($requirement['status'], $requirement['result']); ?> <img
+	src="img/<?php echo $requirement['status'] ? "yes" : "no"; ?>.png" alt="<?php echo $requirement['status'] ? "Succes" : "Failure"; ?>" class="rootimg" /></h4>
```
Comment (MekDrop) [inline htdocs/install/page_modcheck.php]: mistype in 'Success'

File: htdocs/install/page_modcheck.php [hunk 2]
```diff
@@ -63,37 +64,51 @@ function xoDiagIfWritable( $path) {
...
+	$requirement['session']['description']="Session Extension";
+	$requirement['session']['result']=extension_loaded( 'session' ) ? "available" : "missing";
+	$requirement['session']['status']=extension_loaded( 'session' ) ? true : false;
+
+	$requirement['pcre']['description']="PCRE Extension";
+	$requirement['pcre']['result']=extension_loaded( 'PCRE' ) ? "available" : "missing";
+	$requirement['pcre']['status']=extension_loaded( 'PCRE' ) ? true : false;
+
+	$requirement['file_upload']['description']="File uploads";
+	$requirement['file_upload']['result']=xoDiagBoolSetting( 'file_uploads', true ) ? "yes" : "no";
```
Comment (MekDrop) [inline htdocs/install/page_modcheck.php]: I think it's better to use _YES and _NO from global language file instead of "yes" and "no"

File: htdocs/install/page_modcheck.php [hunk 3]
```diff
@@ -63,37 +64,51 @@ function xoDiagIfWritable( $path) {
 	return xoDiag( $error ? -1 : 1, $error ? 'Not writable' : 'Writable' );
 }
 
+function imCheckRequirements()
```
Comment (MekDrop) [inline htdocs/install/page_modcheck.php]: nice solution!

Comment (fiammybe) [reply htdocs/install/page_modcheck.php]: Thanks! I was trying to separate the logic from the presentation. I'm sure it can be improved in further iterations

File: htdocs/install/page_modcheck.php [hunk 4]
```diff
@@ -63,37 +64,51 @@ function xoDiagIfWritable( $path) {
...
-<h4><?php printf( PHP_EXTENSION, 'PCRE' ); ?>:&nbsp; <?php echo xoDiag( extension_loaded( 'pcre' ) ? 1 : -1 ); ?>
-<img src="img/yes.png" alt="Success" class="rootimg" /></h4>
-<div class="clear">&nbsp;</div>
-<h4>file_uploads:&nbsp; <?php echo xoDiagBoolSetting( 'file_uploads', true ); ?>
-<img src="img/yes.png" alt="Success" class="rootimg" /></h4>
+<?php foreach($requirements_array as &$requirement)
+	 {
+	 ?>
+<h4><?php echo $requirement['description']; ?>:&nbsp; <?php echo xoDiag($requirement['status'], $requirement['result']); ?> <img
+	src="img/<?php echo $requirement['status'] ? "yes" : "no"; ?>.png" alt="<?php echo $requirement['status'] ? "Succes" : "Failure"; ?>" class="rootimg" /></h4>
```
[the remark this answers is not in the document]
Comment (fiammybe) [reply htdocs/install/page_modcheck.php]: alt attribute is available, accesslint has issues identifying it

File: htdocs/install/page_modcheck.php (hunk 2 above)
Comment (fiammybe) [reply htdocs/install/page_modcheck.php]: Done

Comment (fiammybe) [reply htdocs/install/page_modcheck.php]: Done

File: htdocs/install/page_modcheck.php (hunk 1 above)
Comment (fiammybe) [reply htdocs/install/page_modcheck.php]: I now use the language constant SUCCESS, which is a better solution

File: htdocs/install/page_modcheck.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (fiammybe) [reply htdocs/install/page_modcheck.php]: alt is there, accesslint just can't see it :-)

File: htdocs/install/page_modcheck.php (hunk 3 above)
Comment (skenow) [reply htdocs/install/page_modcheck.php]: Here is how we were approaching it at the beginning of 2.0 - https://github.com/skenow/impresscms/tree/features/installer2.0/htdocs

File: htdocs/install/page_modcheck.php [hunk 5]
```diff
@@ -63,37 +64,51 @@ function xoDiagIfWritable( $path) {
...
+	if (version_compare( phpversion(), '5.6', '>=')) {
+		$requirement['php_version']['status']=1;
+	} else {
+		$requirement['php_version']['status']=0;
+	}
+	$requirement['php_version']['result']=phpversion();
+
+	$requirement['mysql']['description']="MySQL Handler";
+	$requirement['mysql']['result']=in_array("mysql",PDO::getAvailableDrivers(),TRUE) ? ? SUCCESS : FAILED;
+	$requirement['mysql']['status']=in_array("mysql",PDO::getAvailableDrivers(),TRUE) ? true : false;
```
Comment (skenow) [inline htdocs/install/page_modcheck.php]: There seems to be an extra '?' in line 82

Comment (fiammybe) [reply htdocs/install/page_modcheck.php]: copy-paste error, fixed now.
